name: Android CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Install NDK 27.0.12077973
        run: echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install 'ndk;27.0.12077973'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # - name: Cache NDK
        # uses: actions/cache@v4.2.3
        # with:
          # path: ${ANDROID_HOME}/ndk/27.0.12077973
          # key: ndk-cache

      - name: Fix Permissions for Debug Keystore Path
        if: github.ref != 'refs/heads/main'
        run: sudo chmod -R 777 /home/runner/.config/.android
      
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Release
          path: ${{ github.workspace }}/app/build/outputs/apk/release
